language: node_js
node_js:
  - "10"

branches:
  only:
    - master
    - dev
script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  GITHUB-TOKEN: $github-token  # Set in travis-ci.org dashboard, marked secure
  local_dir: build
  keep-history: true
  on:
branch: master